# Generated by Django 5.1.4 on 2026-09-01 04:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(choices=[('CARGA', 'Archivos cargados'), ('LIMPIEZA', 'Limpieza ejecutada'), ('MAPEO_IA', 'Mapeo propuesto por IA'), ('AJUSTE_HUMANO', 'Ajuste humano del mapeo'), ('TASA_CONFIRMADA', 'Tasa de conversión confirmada'), ('APROBACION', 'Mapeo aprobado'), ('GENERACION', 'Documento generado'), ('ERROR', 'Error registrado')], max_length=20)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='MapeoCampo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen_columna', models.CharField(max_length=150)),
                ('origen_muestra', models.JSONField(blank=True, default=list)),
                ('confianza', models.PositiveSmallIntegerField(default=0)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('ajustado_por_humano', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mapeo_campo',
                'ordering': ['-confianza'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('capitulo', models.CharField(blank=True, max_length=30)),
                ('es_capitulo', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_origen', models.CharField(blank=True, max_length=30)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('requiere_revision', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'partida',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Transformacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_origen', models.FileField(upload_to='origen/%Y/%m/')),
                ('nombre_origen', models.CharField(max_length=255)),
                ('mandante', models.CharField(blank=True, max_length=200)),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='generado/%Y/%m/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('LIMPIEZA', 'Limpieza aplicada'), ('MAPEO_PROPUESTO', 'Mapeo propuesto por IA'), ('EN_REVISION', 'En revisión humana'), ('APROBADO', 'Mapeo aprobado'), ('GENERADO', 'Documento generado'), ('ERROR', 'Error')], default='BORRADOR', max_length=20)),
                ('detalle_error', models.CharField(blank=True, max_length=500)),
                ('confianza', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opciones_limpieza', models.JSONField(blank=True, default=dict)),
                ('resultado_limpieza', models.JSONField(blank=True, default=dict)),
                ('tasa_uf_clp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creada', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transformacion',
                'ordering': ['-creada'],
            },
        ),
    ]
