# Generated by Django 5.1.4 on 2026-09-01 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
        ('plantillas', '0002_initial'),
        ('transformaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapeocampo',
            name='destino_campo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapeos', to='plantillas.campoplantilla'),
        ),
        migrations.AddField(
            model_name='partida',
            name='unidad_canonica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='plantillas.unidadcanonica'),
        ),
        migrations.AddField(
            model_name='transformacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transformacion',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformaciones', to='organizaciones.organizacion'),
        ),
        migrations.AddField(
            model_name='transformacion',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformaciones', to='plantillas.plantilla'),
        ),
        migrations.AddField(
            model_name='partida',
            name='transformacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='transformaciones.transformacion'),
        ),
        migrations.AddField(
            model_name='mapeocampo',
            name='transformacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos', to='transformaciones.transformacion'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='transformacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='transformaciones.transformacion'),
        ),
        migrations.AddIndex(
            model_name='transformacion',
            index=models.Index(fields=['organizacion', '-creada'], name='transformac_organiz_3768eb_idx'),
        ),
        migrations.AddIndex(
            model_name='transformacion',
            index=models.Index(fields=['autor', '-creada'], name='transformac_autor_i_0efed2_idx'),
        ),
        migrations.AddIndex(
            model_name='transformacion',
            index=models.Index(fields=['estado'], name='transformac_estado_02c34f_idx'),
        ),
        migrations.AddIndex(
            model_name='partida',
            index=models.Index(fields=['transformacion', 'orden'], name='partida_transfo_44fd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['transformacion', 'creado'], name='bitacora_transfo_7f7b00_idx'),
        ),
    ]
