# Generated by Django 5.1.4 on 2026-10-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
