# Generated by Django 5.1.4 on 2026-09-01 04:51

import apps.usuarios.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('rol', models.CharField(choices=[('SUPERADMIN', 'Superadministrador'), ('GERENTE', 'Gerente'), ('TRABAJADOR', 'Trabajador')], default='TRABAJADOR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='organizaciones.organizacion')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['nombre_completo'],
            },
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('creada', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira', models.DateTimeField()),
                ('usada_en', models.DateTimeField(blank=True, null=True)),
                ('invitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitacion',
                'ordering': ['-creada'],
            },
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('rol', 'SUPERADMIN'), ('organizacion__isnull', False), _connector='OR'), name='usuario_no_superadmin_requiere_org'),
        ),
    ]
