# Generated by Django 5.1.4 on 2026-09-01 04:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('giro', models.CharField(blank=True, max_length=200)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('anonimizar_montos', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'db_table': 'organizacion',
                'ordering': ['nombre'],
            },
        ),
    ]
