# Generated by Django 5.1.4 on 2026-09-01 04:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPlantilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('columna_excel', models.CharField(blank=True, max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('MONEDA', 'Moneda'), ('FECHA', 'Fecha'), ('UNIDAD', 'Unidad de medida')], default='TEXTO', max_length=10)),
                ('obligatorio', models.BooleanField(default=False)),
                ('moneda_destino', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'campo_plantilla',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('mandante', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('formato', models.CharField(choices=[('XLSX', 'Excel'), ('CSV', 'CSV'), ('PDF', 'PDF'), ('DOCX', 'Word')], default='XLSX', max_length=8)),
                ('archivo', models.FileField(upload_to='plantillas/%Y/%m/')),
                ('hoja_datos', models.CharField(blank=True, default='', max_length=100)),
                ('fila_encabezado', models.PositiveIntegerField(default=1)),
                ('fila_primer_dato', models.PositiveIntegerField(default=2)),
                ('favorita', models.BooleanField(default=False)),
                ('archivada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('usos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'plantilla',
                'ordering': ['-favorita', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadCanonica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('simbolo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('alias', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'unidad_canonica',
                'ordering': ['simbolo'],
            },
        ),
    ]
