# Generated by Django 5.1.4 on 2026-09-01 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
        ('plantillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='organizaciones.organizacion'),
        ),
        migrations.AddField(
            model_name='campoplantilla',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='plantillas.plantilla'),
        ),
        migrations.AddField(
            model_name='unidadcanonica',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='organizaciones.organizacion'),
        ),
        migrations.AddConstraint(
            model_name='campoplantilla',
            constraint=models.UniqueConstraint(fields=('plantilla', 'nombre'), name='campo_unico_por_plantilla'),
        ),
        migrations.AddConstraint(
            model_name='unidadcanonica',
            constraint=models.UniqueConstraint(fields=('organizacion', 'simbolo'), name='unidad_unica_por_organizacion'),
        ),
    ]
