# Generated by Django 5.1.4 on 2026-09-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campoplantilla',
            name='celda_destino',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='campoplantilla',
            name='etiqueta_busqueda',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='campoplantilla',
            name='hoja_destino',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
