# Generated by Django 5.1.4 on 2026-09-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0003_campoplantilla_celda_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campoplantilla',
            name='formato_numero',
            field=models.CharField(blank=True, choices=[('NINGUNO', 'Sin formato (tal cual)'), ('ENTERO', 'Número entero (1.234)'), ('DECIMAL', 'Decimal (1.234,56)'), ('PESOS', 'Pesos chilenos ($ 1.234)'), ('PESOS_DEC', 'Pesos con decimales ($ 1.234,56)'), ('PORCENTAJE', 'Porcentaje (12,5%)'), ('UF', 'UF (1.234,56 UF)')], default='NINGUNO', max_length=12),
        ),
    ]
